THERE ARE 4 LEVELS AND EACH LEVEL HAS 3 LIVES.
INSTRUCTIONS
1)ARROW KEYS FOR BLOCK MOVEMENT
2)B TO CHANEG BLOCK IN 4TH LEVEL
3)V TO CHANEG VIEW
4)MOUSE CONTROLS
5)AUDIO
6)TEXT
7)SPLITTING CUBES STAGE IS ALSO INCLUDED
